//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MastersProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Master_MVCEntities : DbContext
    {
        public Master_MVCEntities()
            : base("name=Master_MVCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_city> tbl_city { get; set; }
        public DbSet<tbl_country> tbl_country { get; set; }
        public DbSet<tbl_login> tbl_login { get; set; }
        public DbSet<tbl_state> tbl_state { get; set; }
        public DbSet<tbl_transaction> tbl_transaction { get; set; }
        public DbSet<tbl_class> tbl_class { get; set; }
        public DbSet<tbl_course> tbl_course { get; set; }
        public DbSet<tbl_subject> tbl_subject { get; set; }
        public DbSet<tbl_studentlistpage> tbl_studentlistpage { get; set; }
    }
}
