//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MastersProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_login
    {
        public long UserID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<long> trans_id { get; set; }
    
        public virtual tbl_transaction tbl_transaction { get; set; }
    }
}
