//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MastersProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_studentlistpage
    {
        public long Studentid { get; set; }
        public string Studentname { get; set; }
        public string Address { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public Nullable<long> Pincode { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string PhoneNumber { get; set; }
        public long Courseid { get; set; }
        public long Classid { get; set; }
        public long Subjectid { get; set; }
        public string Emailid { get; set; }
        public long trans_id { get; set; }
        public string Coursename { get; set; }
        public string Classname { get; set; }
        public string Subjectname { get; set; }
        public long Cid { get; set; }
        public long Sid { get; set; }
        public long Cityid { get; set; }
    
        public virtual tbl_class tbl_class { get; set; }
        public virtual tbl_course tbl_course { get; set; }
        public virtual tbl_subject tbl_subject { get; set; }
        public virtual tbl_transaction tbl_transaction { get; set; }
        public virtual tbl_city tbl_city { get; set; }
        public virtual tbl_country tbl_country { get; set; }
        public virtual tbl_state tbl_state { get; set; }
    }
}
